export default {
    1:require('../assets/img/aboutme/img1.jpg'),
    2:require('../assets/img/aboutme/img2.jpg'),
    3:require('../assets/img/aboutme/img3.jpg'),
    4:require('../assets/img/aboutme/img4.jpg'),
    5:require('../assets/img/aboutme/img5.jpg'),
    6:require('../assets/img/aboutme/img6.jpg'),
    7:require('../assets/img/aboutme/img7.jpg'),
    8:require('../assets/img/aboutme/img8.jpg'),
    9:require('../assets/img/aboutme/img9.jpg'),
    10:require('../assets/img/aboutme/img10.jpg'),
    11:require('../assets/img/aboutme/img11.jpg'),
    12:require('../assets/img/aboutme/img12.jpg'),
    13:require('../assets/img/aboutme/img13.jpg'),
    14:require('../assets/img/aboutme/img14.jpg'),
}